/*.$file${.::main.c} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: blinky.qm
* File:  ${.::main.c}
*
* This code has been generated by QM 5.1.0 <www.state-machine.com/qm/>.
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*.$endhead${.::main.c} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "qpc.h"    /* QP/C framework API */
#include "bsp.h"    /* Board Support Package interface */
#include "esp_log.h"
#include "freertos/FreeRTOS.h"

Q_DEFINE_THIS_FILE

static const char * TAG = "main";

/*
 * small event memory pool
 */
static QF_MPOOL_EL(QEvt) smallPoolSto[CONFIG_QPC_SMALL_POOL_SIZE];

static QEvt const *blinky_queueSto[10]; /* event queue buffer for Blinky */
static StackType_t blinkyStack[2048]; /* Stack size allocation */

/* the main function -------------------------------------------------------*/
int app_main() {
    QF_init();  /* initialize the framework */
    BSP_init(); /* initialize the BSP */

    /* instantiate and start the Blinky active object */
    Blinky_ctor(); /* in C you must explicitly call the Blinky constructor */

    /* Initialize Event Memory Pool */
    QF_poolInit(smallPoolSto, sizeof(smallPoolSto), sizeof(smallPoolSto[0]));

    QActive_setAttr(AO_Blinky, TASK_NAME_ATTR, "Blinky");
    QACTIVE_START(AO_Blinky,     /* AO to start */
        1U,                      /* QP priority of the AO */
        blinky_queueSto,        /* event queue storage */
        Q_DIM(blinky_queueSto), /* queue length [events] */
        blinkyStack,           /* stack storage */
        sizeof(blinkyStack),   /* stack size [bytes] */
        (QEvt *)0);              /* initialization event (not used) */

    return QF_run(); /* let the framework run the application */

    ESP_LOGI(TAG, "Goodbye app_main()");
}